### ISSUE TITLE
Add citation to homepage

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#113]
We will need to add the citation information to the home page. Possibly in a [modal](http://foundation.zurb.com/sites/docs/v/5.5.3/components/reveal.html).

This was mentioned in #112

**Comment by tschaka1904** [comment]
![screen shot 2017-06-14 at 17 24 23](https://user-images.githubusercontent.com/5269116/27143465-5f859c00-5126-11e7-8abe-b01d85047516.png)

**Comment by bmeldal** [comment]
This should be a new page behind the tile because we also need to list all previous and other, related publications such as the Viewer Paper and the XLM3.0 paper that have significant relationships to the CP.

There should then be 2 section: 
"Publications" - which cite all direct CP publications
"Related Publications" - which cite related papers. This could even contain the GOC papers that we were part of as part of the consortium...

**Comment by tschaka1904** [comment]
Please reopen issues, if you think that the ticket hasn't been resolved. Otherwise they will hidden in the depth of closed issues.

**Comment by bmeldal** [comment]
Sorry, clicked wrong "comment" button

**Comment by tschaka1904** [comment]
Based on our earlier discussion, would it be okay to leaf the [modal](http://foundation.zurb.com/sites/docs/v/5.5.3/components/reveal.html) and create a another 'Publications' or maybe 'References' page? We can link from the modal to that page as well.

**Comment by bmeldal** [comment]
Ok, let's try with the link from the modal to a new page that has all citations. Do you want me to add the relevant PMIDs here so you can grab the metadata?
(I'll have to search for the GO paper for example)

**Comment by tschaka1904** [comment]
I'll close this issue and create a new one for the new page.
