### ISSUE TITLE
Pig complexes don't show new GXA data

### ISSUE THREAD

**Issue by bmeldal** [Complex-Portal/complex-portal-view#171]
GXA have released an expt for pig (Sus scrofa) but the widget doesn't show on our website. There should be data for P18434 in EBI-9009119.

http://www.ebi.ac.uk/complexportal/complex/EBI-9009119
https://www.ebi.ac.uk/gxa/genes/ENSSSCG00000009561?bs=%7B%22sus%20scrofa%22%3A%5B%22ORGANISM_PART%22%5D%7D#baseline

**Comment by tschaka1904** [comment]
This is happening, because we haven't defined the baseline experiment for _Pig_. Here is a list of the baseline experiments: 
- Homo sapiens; 9606 = E-MTAB-5214
- Mus musculus; 10090 = E-MTAB-4644
- Rattus norvegicus; 10116 = E-GEOD-53960
- Gallus gallus (Chicken); 9031 = E-MTAB-2797
- Caenorhabditis elegans; 6239 = E-MTAB-2812

**Comment by tschaka1904** [comment]
If you want to add _Pig_, please provide the baseline experiment. I think the person to talk to is Irene Papatheodorou.

**Comment by bmeldal** [comment]
Should be this one, the only baseline expt for pig in GXA so far:
https://www.ebi.ac.uk/gxa/experiments/E-MTAB-5895/Results
**E-MTAB-5895**

**Comment by tschaka1904** [comment]
I've added it, but there is a problem with the viewer. The complex has three participants and sends the request with all participant IDs. Anyway, it seems to 'AND' the IDs rather to 'OR' them. So the result it an error when asking all three IDs. I've contacted the GXA team for assistance.

**Comment by bmeldal** [comment]
Thanks.

**Comment by bmeldal** [comment]
I think this is fixed.
