### ISSUE TITLE
CPX-3070 participant graph

### ISSUE THREAD

**Issue by edwong57** [Complex-Portal/complex-portal-view#188]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**

'yos9_yeast' is cut off in the graph, and is displaying 'os9_yeast'

**Expected behaviour**

participant's whole name should be shown.

**Minimal reproduction of the problem with instructions**

![image](https://user-images.githubusercontent.com/526428/46177747-ea69f500-c268-11e8-8168-9c595d35048a.png)

**What is the motivation / use case for changing the behaviour?**

Just checking out the complex pages and noticed this.

**Please tell us about your environment:**

 Mac OS 10.13.6; Firefox 62.0

**Comment by bmeldal** [comment]
Hi Edith,

We display the Uniprot name rather than the gene symbol (a change is on our to-do list) and strangely enough, the Uniprot name is OS9_YEAST. I'm not sure Uniprot would change it but you are right, it looks really odd.

![image](https://user-images.githubusercontent.com/10517124/46192772-19797880-c2f4-11e8-96a9-3de050da30ec.png)


Birgit

**Comment by edwong57** [comment]
Hi Birgit,


Ah, okay. That makes sense now. Thanks for that explanation.

Have a great weekend!
Edith


________________________________
