### ISSUE TITLE
Pathway Diagram selects whole pathway

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#31]
Based on issue #23 

> Ok, it's back, but there is another issue that needs fixing with them:
> https://complex-portal.github.io/complex-portal-view/complex/EBI-1245484
> The complex is only one element of the diagram but the whole assembly process is highlighted making the diagram too small and unreadable. Even on the Reactome site it highlights too many elements.

**Comment by tschaka1904** [comment]
@bmeldal 

I think there are two issues here. One is that the diagram is to small on the new CP site. The other one is that it is not selecting the right element in the PW Diagram, isn't it?

**Comment by bmeldal** [comment]
Yes, in some cases the diagram area is too small but if Reactome didn't force the highlighting of the reaction(s) that produce the complex it could zoom in further.

In some cases (eg PCNA, [EBI-1202920](https://complex-portal.github.io/complex-portal-view/complex/EBI-1202920)) the complex is part of bigger complexes and there are lots of instances in the same diagram. It'll be hard to now how far to zoom in!

In other cases it shows the illustration and not the diagram - This also happens on the Reactome site and I can't get into the diagram right now. Eg [EBI-11665013](https://complex-portal.github.io/complex-portal-view/complex/EBI-11665013) (IL12 receptor) - open issue on Reactome tracker?

**Comment by tschaka1904** [comment]
Hi @fabregat

we have a few issues regarding the PW Diagram and how it selects the entities. @bmeldal has pointed out some examples.

**Comment by fabregat** [comment]
Hi @tschaka1904, @bmeldal,

For the first case, it looks like a race condition between the subpathway selection and the complex selection. To achieve the result you aim, please ensure that you subscribe to the onDiagramLoaded event and your code runs with a schedule deferred to allow other subscribers to run first.

The second case is because the EHLDs in ReactomeDev have been designed following the content for next data release (v60) and your example is pointing to one case where there are differences in the data content between current version (v59) and next version (v60).

So, first problem requieres a little bit of change in your code and the second one just requires a little bit of patience until v60 is released :)

Cheers!

**Comment by tschaka1904** [comment]
Okay. I did some further investigation on this. If I use the `diagram.nocache.js` from [www.reactome.org](http://www.reactome.org/) it works nicely. 
![ebi-1202920](https://cloud.githubusercontent.com/assets/5269116/23360807/5d169a18-fce5-11e6-9b5b-abbb53868c2e.png)

Using the the `diagram.nocache.js` from [reactomedev.oicr.on.ca](https://reactomedev.oicr.on.ca) it doesn't work.
![ebi-1202920_broken](https://cloud.githubusercontent.com/assets/5269116/23360890/be11d47c-fce5-11e6-84ad-5e0cf4f50bfc.png)

**Comment by fabregat** [comment]
This is now fixed.

Thank you for reporting 👍

**Comment by tschaka1904** [comment]
Thanks a lot! I'll close this issue, since the other problem will solve itself with the new Reactome release.
